# Generated by Django 5.2.1 on 2025-06-09 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='400405050', help_text='الزامی است، شروع با 40', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Student ID must be a 9-digit number starting with '40'.", regex='^40\\d{7}$')], verbose_name='شماره دانشجویی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be an 11-digit number starting with '09'.", regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
