# Generated by Django 5.2.1 on 2025-06-09 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_student_id_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(help_text='الزامی است، شروع با 40', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Student ID must be a 9-digit number starting with '40'.", regex='^40\\d{7}$')], verbose_name='شماره دانشجویی'),
        ),
    ]
