# Generated by Django 5.2.1 on 2025-06-09 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='شماره وارد شده معتبر نیست', regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(help_text='الزامی است، شروع با 40', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='شماره دانشجویی معتبر نیست', regex='^40\\d{7}$')], verbose_name='شماره دانشجویی'),
        ),
    ]
