# Generated by Django 5.2.1 on 2025-05-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_item', models.BooleanField(default=True, verbose_name='کالا')),
                ('is_service', models.BooleanField(default=False, verbose_name='خدمات')),
            ],
            options={
                'verbose_name': 'واحد تبادل',
                'db_table': 'currencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'فعال'), ('matched', 'انجام شده'), ('closed', 'غیرفعال')], default='open', max_length=20, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
            ],
            options={
                'verbose_name': 'آگهی',
                'db_table': 'offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfferProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
            ],
            options={
                'verbose_name': 'آگهی\u200cهای داری متقاضی',
                'db_table': 'offer_proposal',
                'managed': False,
            },
        ),
    ]
