# Generated by Django 5.2.1 on 2025-05-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'managed': False, 'verbose_name': 'واحد تبادل', 'verbose_name_plural': 'واحدهای تبادل'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'managed': False, 'verbose_name': 'آگهی', 'verbose_name_plural': 'آگهی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='offerproposal',
            options={'managed': False, 'verbose_name': 'آگهی\u200c داری متقاضی', 'verbose_name_plural': 'آگهی\u200cهای دارای متقاضی'},
        ),
    ]
