# Generated by Django 5.2.1 on 2025-05-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_currency_options_alter_offer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'آگهی', 'verbose_name_plural': 'آگهی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='offerproposal',
            options={'verbose_name': 'پیشنهاد آگهی', 'verbose_name_plural': 'پیشنهادهای آگهی'},
        ),
    ]
