# Generated by Django 5.2.1 on 2025-05-28 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_offer_options_alter_offerproposal_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'managed': False, 'verbose_name': 'آگهی', 'verbose_name_plural': 'آگهی\u200cها'},
        ),
        migrations.AddField(
            model_name='offerproposal',
            name='offer_id',
            field=models.ForeignKey(blank=True, db_column='offer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='exchange.offer', verbose_name='شماره آگهی'),
        ),
        migrations.AddField(
            model_name='offerproposal',
            name='proposed_currency',
            field=models.ForeignKey(blank=True, db_column='proposed_currency', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.currency', verbose_name='واحد پیشنهادی'),
        ),
        migrations.AddField(
            model_name='offerproposal',
            name='proposer_id',
            field=models.ForeignKey(blank=True, db_column='proposer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='متقاضی'),
        ),
    ]
