# Generated by Django 5.2.1 on 2025-06-09 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tradeable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('type', models.CharField(choices=[('item', 'کالا'), ('service', 'خدمات')], default='item', max_length=15, verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'واحد تبادل',
                'verbose_name_plural': 'واحدهای تبادل',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'فعال'), ('matched', 'انجام شده'), ('closed', 'غیرفعال')], default='open', max_length=20, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='پیشنهاد دهنده')),
                ('to_get', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_to_get', to='barter.tradeable', verbose_name='تقاضا')),
                ('to_give', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_to_give', to='barter.tradeable', verbose_name='عرضه')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'انتظار'), ('ACCEPTED', 'پذیرفته شده'), ('DECLINED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='barter.offer', verbose_name='شماره آگهی')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='متقاضی')),
                ('proposed_tradeable', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barter.tradeable', verbose_name='واحد پیشنهادی')),
            ],
            options={
                'verbose_name': 'پیشنهاد آگهی',
                'verbose_name_plural': 'پیشنهادهای آگهی',
            },
        ),
    ]
