# Generated by Django 5.2.1 on 2025-06-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offered_by',
            new_name='owner',
        ),
    ]
