# Generated by Django 5.2.1 on 2025-06-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0002_rename_offered_by_offer_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tradeables/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('open', 'فعال'), ('done', 'انجام شده'), ('closed', 'غیرفعال')], default='open', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'انتظار'), ('accepted', 'پذیرفته شده'), ('declined', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
