# Generated by Django 5.2.1 on 2025-05-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
            ],
            options={
                'verbose_name': 'نظر',
                'db_table': 'comments',
                'managed': False,
            },
        ),
    ]
